name: Check Licenses
on: [pull_request]
jobs:
  check-licenses:
    runs-on: [self-hosted]
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb # v4
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@d7b04341511764175f0caa9ca95812db2a02c4a3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam pin . --no-action
      - run: opam depext conf-protoc --yes --with-doc --with-test
      - run: opam install . --deps-only --with-doc --with-test
      - uses: BendingSpoons/github-actions/check-licenses@d6de2dd025713ce457cf407b109476f0c46c4764
        with:
          license-config-github-token: ${{ secrets.LICENSE_CONFIG_GITHUB_TOKEN }}
          scope: external
